# Generated by Django 3.1.4 on 2021-01-01 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BatteryType',
        ),
    ]
