# Generated by Django 3.1.4 on 2021-01-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batterytype',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
