# Generated by Django 3.1.4 on 2021-01-01 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0005_batterymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BatteryAssignment',
        ),
    ]
