# Generated by Django 3.1.4 on 2021-01-01 17:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('battery', '0006_delete_batteryassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_model_qty', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('battery_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battery.batterymodel')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battery.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
