# Generated by Django 3.1.5 on 2021-01-24 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0007_batteryassignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batteryassignment',
            old_name='battery_model_qty',
            new_name='battery_qty',
        ),
    ]
